QwertySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('projects/', include('reader.urls')),
    path('accounts/', include('accounts.urls')),

]

handler404 = 'pages.views.not_found'
handler500 = 'pages.views.not_found'

pages/urls.py
# pages.urls.py

from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about-us/', views.aboutUs, name='aboutUs'),
    path('recruitment/', views.recruit, name='recruit'),
    path('recruitment/<msg>/', views.recruit, name='recruit'),
    path('recruit-form/', views.recruitForm, name='recruitForm'),
    path('contact-us/', views.contactUs, name='contactUs'),
    path('contact-us/<msg>/', views.contactUs, name='contactUs'),
    path('contact-form/', views.contactForm, name='contactForm'),
]

reader/urls.py
# reader.urls.py

from django.urls import path

from . import views

app_name = 'reader'
urlpatterns = [
    path('', views.index, name='index'),
    path('<mangaSeries>', views.mangaDetail, name='mangaDetail'),
    path('<mangaSeries>/<int:chapterId>/readChapter/', views.readChapter, name='readChapter'),
    path('<mangaSeries>/<int:chapterId>', views.stripReader, name='stripReader'),
    path('<mangaSeries>/<int:chapterId>/<int:pageNum>', views.pageReader, name='pageReader'),
    path('<mangaSeries>/jump/<display>', views.jumpChapter, name='jumpChapter'),
    path('<mangaSeries>/<int:chapterId>/jump', views.jumpPage, name='jumpPage'),
    path('upload/', views.upload, name='upload'),
    path('upload/<chapterUploaded>', views.upload, name='upload'),
    path('upload/submit_chapter/', views.submitChapter, name='submitChapter'),

]

pages/templates/pages/about_us.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>QWERTY Scans | About Us</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pages/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="header">
      <div class="container">
        <a href="{% url 'pages:home' %}">
          <h1>QWERTY Scans</h1>
        </a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <a class="btn" href="{% url 'pages:home' %}">Home</a>
          <a class="btn selected" href="{% url 'pages:aboutUs' %}">About</a>
          <a class="btn" href="{% url 'reader:index' %}">Projects</a>
          <a class="btn" href="{% url 'pages:recruit' %}">Recruitment</a>
          <a class="btn" href="{% url 'pages:contactUs' %}">Contact Us</a>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <h2>About Us</h2>
        <p>QWERTY Scans (the first 6 letters on the keyboard) was founded by Korsia and Rei on April 24, 2017. Our main focus is to balance out the speed and quality of each chapter release. We are an active scanlation group that simply wants to give back to the manga/webtoon community!</p>
        <br/><br/>
        <h3>FAQ</h3>
        <h4>I'm bored. What should I do?</h4>
        <p>You should <a hred="recruitment.html">join QWERTY Scans</a> and help us translate comics and get more releases out!</p>
        <h4>Why QWERTY</h4>
        <p>We are amazing people who will never fail to make your day, only the best are amongst our ranks.</p>
        <h4>What does QWERTY mean?</h4>
        <p>QWERTY is simply the first 6 keys on your keyboard going from left to right. It is simple to remember and easy to type.</p>
      </div>
    </div>

    <div class="footer">
      <div class="container">
        <p>Disclaimer: The all the series worked on here is the property of the original author/artist. <br> QWERTY Scans is not an official distributor. If you like the series, please consider supporting the author by visiting the official site.</p>
      </div>
    </div>
  </body>
</html>

pages/templates/pages/contact_us.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>QWERTY Scans | Contact Us</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pages/forms.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pages/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="header">
      <div class="container">
        <a href="{% url 'pages:home' %}">
          <h1>QWERTY Scans</h1>
        </a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <a class="btn" href="{% url 'pages:home' %}">Home</a>
          <a class="btn" href="{% url 'pages:aboutUs' %}">About</a>
          <a class="btn" href="{% url 'reader:index' %}">Projects</a>
          <a class="btn" href="{% url 'pages:recruit' %}">Recruitment</a>
          <a class="btn selected" href="{% url 'pages:contactUs' %}">Contact Us</a>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <h2>Contact Us</h2>
        <p>Contact us here with any questions, comments, or suggestions.</p>
        <p>You can also visit us at <a href="https://www.facebook.com/QwertyScans/" target="_blank">Facebook</a> and/or <a href="https://discordapp.com/invite/65yGM9w" target="_blank">Discord</a>!</p>
        <br/>

        <div class="form">
          {% if msg %}
            <p style="color: blue;">{{ msg }}</p>
            <br/>
          {% endif %}
          <form action="{% url 'pages:contactForm' %}" method="post">
            {% csrf_token %}
            <label for="name">Name </label><label style="color: red;">*</label><br/>
            <input type="text" id="name" name="name" required>
            <br/>
            <label for="email">Email </label><label style="color: red;">*</label><br/>
            <input type="text" id="email" name="email" required>
            <br/>
            <label for="comment">Comment </label><label style="color: red;">*</label><br/>
            <textarea id="comment" name="comment" style="height:200px" required></textarea>
            <br/>
            <input type="submit" value="Submit">
          </form>
        </div>
      </div>
    </div>

    <div class="footer">
      <div class="container">
        <p>Disclaimer: The all the series worked on here is the property of the original author/artist. <br> QWERTY Scans is not an official distributor. If you like the series, please consider supporting the author by visiting the official site.</p>
      </div>
    </div>
  </body>
</html>

pages/templates/pages/home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>QWERTY Scans</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pages/float.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pages/blogPosts.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pages/jumbotron.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pages/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="header">
      <div class="container">
        <a href="{% url 'pages:home' %}">
          <h1>QWERTY Scans</h1>
        </a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <a class="btn selected" href="{% url 'pages:home' %}">Home</a>
          <a class="btn" href="{% url 'pages:aboutUs' %}">About</a>
          <a class="btn" href="{% url 'reader:index' %}">Projects</a>
          <a class="btn" href="{% url 'pages:recruit' %}">Recruitment</a>
          <a class="btn" href="{% url 'pages:contactUs' %}">Contact Us</a>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <div class="floatSide">
          <h3>Latest Updates</h3>
          {% if chapter_list %}
            {% for chapter in chapter_list %}
              <a href="{% url 'reader:readChapter' chapter.manga.storage_name chapter.id %}">{{ chapter.manga.title }} {{ chapter }}</a>
              <br/>
            {% endfor %}
          {% endif %}
        </div>
        <div class="floatMain">
          {% if pinned_list %}
            {% for blog in pinned_list %}
              <div class="pinnedPost">
                <h2>{{ blog.title }}</h2>
                <h5>{{ blog.getCategory }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ blog.created_date }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ blog.writer }}</h5>    
                <p>{{ blog.post|safe }}</p>
              </div>
            {% endfor %}
          {% endif %}
          {% if blog_list %}
            {% for blog in blog_list %}
              <div class="blogPost">
                <h2>{{ blog.title }}</h2>
                <h5>{{ blog.getCategory }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ blog.created_date }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ blog.writer }}</h5>    
                <p>{{ blog.post|safe }}</p>
              </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>

      <div class="container">
        <div id="disqus_thread"></div>
      </div>
    </div>

    <!--div class="jumbotron">
      <div class="container">
        <h2>Join Qwerty</h2>
        <p>Help us get releases out faster.</p>
        <a class="btn" href="{% url 'pages:recruit' %}">Recruitment</a>
      </div>
    </div-->
   
    <script>
 
    /** 
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    
    var disqus_config = function () {
      this.page.url = 'https://qwertyscans.com';  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = 'homePage'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    
    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://qwerty-scans.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>    

    <div class="footer">
      <div class="container">
        <p>Disclaimer: The all the series worked on here is the property of the original author/artist. <br> QWERTY Scans is not an official distributor. If you like the series, please consider supporting the author by visiting the official site.</p>
      </div>
    </div>
  <script id="dsq-count-scr" src="//qwerty-scans.disqus.com/count.js" async></script>
  </body>
</html>

pages/templates/pages/recruitment.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>QWERTY Scans | Recruitment</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'pages/forms.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pages/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="header">
      <div class="container">
        <a href="{% url 'pages:home' %}">
          <h1>QWERTY Scans</h1>
        </a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <a class="btn" href="{% url 'pages:home' %}">Home</a>
          <a class="btn" href="{% url 'pages:aboutUs' %}">About</a>
          <a class="btn" href="{% url 'reader:index' %}">Projects</a>
          <a class="btn selected" href="{% url 'pages:recruit' %}">Recruitment</a>
          <a class="btn" href="{% url 'pages:contactUs' %}">Contact Us</a>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <h2>Recruitment</h2>
        <h3>Thank you for thinking about joining QWERTY Scans!</h3>
        <p>To apply, you will need to fill out the form below and submit it to us. We will then take a look and contact you about the position you’re interested in.</p>
        <p>*** This is <strong>volunteer</strong> only, our staff gets no monetary compensation whatsoever.</p>
        <p>We are currently <strong>ONLY</strong> looking for <strong>Korean Translators</strong>!!!</p>
        <!--<p>You will find a list of the positions we are currently looking for <strong><a href="https://docs.google.com/spreadsheets/d/1LIpss8YSdX4fgD8RWl_N-rWeoldQh0wpCQ3m0Y_XxFA/edit?usp=sharing" target="_blank">HERE</a></strong> and a description of the positions below.</p>-->
        <h3>Positions</h3>
        <p><strong>Assistant</strong><br>Helps pull raws from sources and assists other people when needed. Mostly there for moral support.</p>
        <p><strong>Translator</strong><br>Must be proficient in both the language being translated from and English. Responsible for translating the original script into English while keeping the script as close as possible to the original meaning.<br></p>
        <!--del-->
        <p><strong>Proofreader</strong><br>Responsible for correcting any grammar mistakes and improving overall flow of the script while maintaining the original meaning of the translation. Meant for Grammar Nazis.</p>
        <!--/del-->
        <p><strong>Cleaner</strong><br>Takes out all text in bubbles and outside the bubbles, such as sfx or any dialogue outside the bubbles. Will need to be able to redraw any parts taken out. Perfect for artists or aspiring artists.</p>
        <p><strong>Redrawer</strong><br>Redraws any part of the page that has been erased or taken out due to cleaning. This position is meant for artists who think they are good at drawing.</p>
        <p><strong>Typesetter</strong><br>Replaces the old script with the newly translated English script by copying and pasting text into the correct bubbles and panels. Must be very skilled with copy and paste, ideal for font fanatics.</p>
        <p><strong>Editor</strong><br>Someone who can both typeset and clean. A multi-talented person.</p>
        <br/>

        <div class="form">
          <h3>Please fill out the following:</h3>
          {% if msg %}
            <p style="color: blue;">{{ msg }}</p>
            <br/>
          {% endif %}
          <form action="{% url 'pages:recruitForm' %}" method="post">
            {% csrf_token %}
            <div class="formLabel"><label for="name">Name </label><label style="color: red;">*</label></div>
            <input type="text" id="name" name="name" required>
            <br/><br/>

            <div class="formLabel"><label for="email">Email </label><label style="color: red;">*</label></div>
            <input type="text" id="email" name="email" required>
            <br/><br/>

            <div class="formLabel"><label for="position">Desired Position </label><label style="color: red;">*</label></div>
             <!--  <input type="radio" id="assistant" name="position" value="Assistant" required><label for="assistant">&nbsp;&nbsp;Assistant</label><br/> -->
              <input type="radio" id="ktl" name="position" value="Korean Translator"><label for="ktl">&nbsp;&nbsp;Korean Translator</label><br/>
              <!-- <input type="radio" id="jtl" name="position" value="Japanese Translator"><label for="jtl">&nbsp;&nbsp;Japanese Translator</label><br/>
              <input type="radio" id="ctl" name="position" value="Chinese Translator"><label for="ctl">&nbsp;&nbsp;Chinese Translator</label><br/>
              <input type="radio" id="proofreader" name="position" value="Proofreader"><label for="proofreader">&nbsp;&nbsp;Proofreader</label><br/>
              <input type="radio" id="cleaner" name="position" value="Cleaner"><label for="cleaner">&nbsp;&nbsp;Cleaner</label><br/>
              <input type="radio" id="redrawer" name="position" value="Redrawer"><label for="redrawer">&nbsp;&nbsp;Redrawer</label><br/>
              <input type="radio" id="typesetter" name="position" value="Typesetter"><label for="typesetter">&nbsp;&nbsp;Typesetter</label><br/>
              <input type="radio" id="editor" name="position" value="Editor"><label for="editor">&nbsp;&nbsp;Editor</label><br/> -->
            <br/><br/>

            <div class="formLabel"><label for="experience">Do you have experience with the position you selected? </label><label style="color: red;">*</label></div>
              <input type="radio" id="yes" name="experience" value="Yes" required><label for="yes">&nbsp;&nbsp;Yes</label><br/>
              <input type="radio" id="no" name="experience" value="No"><label for="no">&nbsp;&nbsp;No</label><br/>
            <br/><br/>

            <div class="formLabel"><label for="groups">Are you in any other groups? If yes, please list them below. If no, skip this question. </label></div>
            <textarea id="groups" name="groups" style="height:200px"></textarea>
            <br/><br/>

            <div class="formLabel"><label for="projects">What project are you interested in working on? </label><label style="color: red;">*</label><label></br><em>Note: This does NOT guarantee that you will be able to work on those projects. Assignment will be based on project availability and skill levels.</em></label></div>
            <textarea id="projects" name="projects" style="height:200px" required></textarea>
            <br/><br/>

            <div class="formLabel"><label for="selfintro">Tell us a bit about yourself. </label><label style="color: red;">*</label></div>
            <textarea id="selfintro" name="selfintro" style="height:200px" required></textarea>
            <br/><br/>

            <div class="formLabel"><label for="discovery">How did you discover us? </label><label style="color: red;">*</label></div>
            <textarea id="discovery" name="discovery" style="height:200px" required></textarea>
            <br/><br/>

            <div class="formLabel"><label for="reason">Why do you want to join our team? </label><label style="color: red;">*</label></div>
            <textarea id="reason" name="reason" style="height:200px" required></textarea>
            <br/><br/>

            <div class="formLabel"><label for="comment">Is there anything else you want to tell us? Questions, comments, past experience, whether or not you are applying for another position. </label></div>
            <textarea id="comment" name="comment" style="height:200px"></textarea>
            <br/><br/>

            <input type="submit" value="Submit">
          </form>
        </div>
      </div>

      </div>
    </div>

    <div class="footer">
      <div class="container">
        <p>Disclaimer: The all the series worked on here is the property of the original author/artist. <br> QWERTY Scans is not an official distributor. If you like the series, please consider supporting the author by visiting the official site.</p>
      </div>
    </div>
  </body>
</html>