QwertySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('projects/', include('reader.urls')),
    path('accounts/', include('accounts.urls')),

]

handler404 = 'pages.views.not_found'
handler500 = 'pages.views.not_found'

accounts/urls.py
# reader.urls.py

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.logout, {'next_page': 'reader:index'}, name='logout'),

]

pages/urls.py
# pages.urls.py

from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about-us/', views.aboutUs, name='aboutUs'),
    path('recruitment/', views.recruit, name='recruit'),
    path('recruitment/<msg>/', views.recruit, name='recruit'),
    path('recruit-form/', views.recruitForm, name='recruitForm'),
    path('contact-us/', views.contactUs, name='contactUs'),
    path('contact-us/<msg>/', views.contactUs, name='contactUs'),
    path('contact-form/', views.contactForm, name='contactForm'),
]

reader/urls.py
# reader.urls.py

from django.urls import path

from . import views

app_name = 'reader'
urlpatterns = [
    path('', views.index, name='index'),
    path('<mangaSeries>', views.mangaDetail, name='mangaDetail'),
    path('<mangaSeries>/<int:chapterId>/readChapter/', views.readChapter, name='readChapter'),
    path('<mangaSeries>/<int:chapterId>', views.stripReader, name='stripReader'),
    path('<mangaSeries>/<int:chapterId>/<int:pageNum>', views.pageReader, name='pageReader'),
    path('<mangaSeries>/jump/<display>', views.jumpChapter, name='jumpChapter'),
    path('<mangaSeries>/<int:chapterId>/jump', views.jumpPage, name='jumpPage'),
    path('upload/', views.upload, name='upload'),
    path('upload/<chapterUploaded>', views.upload, name='upload'),
    path('upload/submit_chapter/', views.submitChapter, name='submitChapter'),

]

reader/models.py
from django.db import models
from django.contrib import auth


# Create your models here.

class Manga(models.Model):
    title = models.CharField(max_length=200, blank=False, unique=True)
    alternative_titles = models.CharField(max_length=200, blank=True)
    author = models.CharField(max_length=50, blank=False)
    artist = models.CharField(max_length=50, blank=False)
    description = models.CharField(max_length=1000, blank=False)
    language = models.CharField(max_length=100, blank=True)
    genres = models.CharField(max_length=100, blank=True)
    COMPLETED = 'CP'
    CURRENT = 'CU'
    HIATUS = 'HT'
    DROPPED = 'DP'
    FUTURE = 'FT'
    LITC = 'LC'
    status_choices = (
        (COMPLETED, 'Completed'),
        (CURRENT, 'Current'),
        (HIATUS, 'Hiatus'),
        (DROPPED, 'Dropped'),
        (FUTURE, 'Future'),
        (LITC, "Lost in the Clouds"),
    )
    status = models.CharField(max_length=2, choices=status_choices, default=CURRENT)
    is_joint = models.BooleanField(default=False)
    joints = models.CharField(max_length=200, blank=True)
    TRADITIONAL = 0
    WEBTOON = 1
    display_choices = (
        (TRADITIONAL, 'Traditional (pages)'),
        (WEBTOON, 'Webtoon (strip view)'),
    )
    display_method = models.PositiveSmallIntegerField(choices=display_choices, default=WEBTOON)
    pic_location = models.CharField(max_length=200, blank=False)
    storage_name = models.CharField(max_length=100, blank=False, unique=True)

    def __str__(self):
        return self.title


class Chapter(models.Model):
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE)
    chap_number = models.DecimalField(max_digits=5, decimal_places=2)
    vol_number = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    sort_number = models.PositiveIntegerField()
    title = models.CharField(max_length=200, blank=True)
    num_pages = models.PositiveSmallIntegerField()
    owner = models.ForeignKey(auth.models.User, on_delete=models.SET_NULL, null=True)
    upload_date = models.DateTimeField('date uploaded', editable=False)
    visible = models.BooleanField(default=True)
    storage_name = models.CharField(max_length=100, blank=False)

    def __str__(self):
        displayName = "Chapter {0}".format(
            str(round(float(self.chap_number), 2) if float(self.chap_number) % 1 else int(self.chap_number)))
        if self.vol_number != 0:
            displayName = "Volume {0} {1}".format(
                str(round(float(self.vol_number), 1) if float(self.vol_number) % 1 else int(self.vol_number)),
                displayName)
        if self.title != "":
            displayName = displayName + ": " + self.title
        return displayName

    def getDisplay(self):
        displayName = "Chapter {0}".format(
            str(round(float(self.chap_number), 1) if float(self.chap_number) % 1 else int(self.chap_number)))
        if self.vol_number != 0:
            displayName = "Volume {0} {1}".format(
                str(round(float(self.vol_number), 1) if float(self.vol_number) % 1 else int(self.vol_number)),
                displayName)
        displayName = self.manga.title + " " + displayName
        return displayName


class Page(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    number = models.PositiveSmallIntegerField()
    image = models.ImageField(max_length=200, blank=False)

reader/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.db import models
from django.contrib.auth.decorators import permission_required

from .models import Manga, Chapter, Page

import os, errno, zipfile
import re


# Create your views here.

def index(request):
    currentList = Manga.objects.all().filter(status=Manga.CURRENT).order_by('title')[:]
    completedList = Manga.objects.all().filter(status=Manga.COMPLETED).order_by('title')[:]
    hiatusList = Manga.objects.all().filter(status=Manga.HIATUS).order_by('title')[:]
    droppedList = Manga.objects.all().filter(status=Manga.DROPPED).order_by('title')[:]
    futureList = Manga.objects.all().filter(status=Manga.FUTURE).order_by('title')[:]
    litcList = Manga.objects.all().filter(status=Manga.LITC).order_by('title')[:]

    context = {}
    if len(currentList) != 0:
        context['current_list'] = currentList
    if len(completedList) != 0:
        context['completed_list'] = completedList
    if len(hiatusList) != 0:
        context['hiatus_list'] = hiatusList
    if len(droppedList) != 0:
        context['dropped_list'] = droppedList
    if len(futureList) != 0:
        context['future_list'] = futureList
    if len(litcList) != 0:
        context['litc_list'] = litcList

    return render(request, 'reader/index.html', context)


def mangaDetail(request, mangaSeries):
    try:
        manga = Manga.objects.get(storage_name=mangaSeries)
    except(KeyError, Manga.DoesNotExist):
        render(request, 'reader/index.html')
    chapterList = manga.chapter_set.filter(visible=True).order_by('-sort_number')[:]
    context = {
        'manga': manga,
        'chapter_list': chapterList,
    }
    return render(request, 'reader/manga_details.html', context)


def readChapter(request, mangaSeries, chapterId):
    try:
        manga = Manga.objects.get(storage_name=mangaSeries)
    except(KeyError, Manga.DoesNotExist):
        render(request, 'reader/index.html')
    try:
        chapter = Chapter.objects.get(pk=chapterId)
    except(KeyError, Chapter.DoesNotExist):
        raise Http404("Chapter does not exist")
    if manga.display_method == Manga.TRADITIONAL:
        return HttpResponseRedirect(reverse('reader:pageReader', args=(mangaSeries, chapterId, 1,)))
    elif manga.display_method == Manga.WEBTOON:
        return HttpResponseRedirect(reverse('reader:stripReader', args=(mangaSeries, chapterId,)))


def stripReader(request, mangaSeries, chapterId):
    try:
        manga = Manga.objects.get(storage_name=mangaSeries)
    except(KeyError, Manga.DoesNotExist):
        render(request, 'reader/index.html')
    try:
        chapter = Chapter.objects.get(pk=chapterId)
    except(KeyError, Chapter.DoesNotExist):
        raise Http404("Chapter does not exist")

    chapterList = manga.chapter_set.filter(visible=True).order_by('sort_number')[:]
    hasPrev = False
    hasNext = False
    prevId = 0
    nextId = 0
    chapLen = len(chapterList)
    for i in range(0, chapLen):
        if chapterList[i] == chapter:
            if (i != chapLen - 1):
                nextId = chapterList[i + 1].id
                hasNext = True
            if (i != 0):
                prevId = chapterList[i - 1].id
                hasPrev = True
            break

    pageList = chapter.page_set.order_by('number')[:]
    pageUrls = []
    for page in pageList:
        strurl = str(page.image)
        pageUrls.append(strurl)

    context = {
        'manga': manga,
        'chapter': chapter,
        'chapter_list': chapterList,
        'prev_id': prevId,
        'next_id': nextId,
        'page_list': pageUrls,
    }
    if hasPrev and (not hasNext):
        context = {
            'manga': manga,
            'chapter': chapter,
            'chapter_list': chapterList,
            'prev_id': prevId,
            'page_list': pageUrls,
        }
    elif hasNext and (not hasPrev):
        context = {
            'manga': manga,
            'chapter': chapter,
            'chapter_list': chapterList,
            'next_id': nextId,
            'page_list': pageUrls,
        }
    elif (not hasNext) and (not hasPrev):
        context = {
            'manga': manga,
            'chapter': chapter,
            'chapter_list': chapterList,
            'page_list': pageUrls,
        }

    return render(request, 'reader/stripReader.html', context)


def pageReader(request, mangaSeries, chapterId, pageNum):
    try:
        manga = Manga.objects.get(storage_name=mangaSeries)
    except(KeyError, Manga.DoesNotExist):
        render(request, 'reader/index.html')
    try:
        chapter = Chapter.objects.get(pk=chapterId)
    except(KeyError, Chapter.DoesNotExist):
        raise Http404("Chapter does not exist")
    try:
        page = chapter.page_set.get(number=pageNum)
    except(KeyError, Page.DoesNotExist):
        raise Http404("Page does not exist")

    pageUrl = str(page.image)
    pageList = [i for i in range(1, chapter.num_pages + 1)]

    hasNextPage = True
    hasPrevPage = True
    hasNextChap = False
    hasPrevChap = False
    prevPage = pageNum - 1
    nextPage = pageNum + 1
    prevChapId = 0
    nextChapId = 0
    prevChapNum = 0

    chapterList = manga.chapter_set.filter(visible=True).order_by('sort_number')[:]
    hasPrev = False
    hasNext = False
    chapLen = len(chapterList)
    for i in range(0, chapLen):
        if chapterList[i] == chapter:
            if (i != chapLen - 1):
                nextChapId = chapterList[i + 1].id
                hasNext = True
            if (i != 0):
                prevChapId = chapterList[i - 1].id
                hasPrev = True
                prevChapNum = chapterList[i - 1].num_pages
            break

    if pageNum == chapter.num_pages or pageNum == 1:
        if pageNum == chapter.num_pages:
            hasNextPage = False
            if hasNext:
                hasNextChap = True
        if pageNum == 1:
            hasPrevPage = False
            if hasPrev:
                hasPrevChap = True

    context = {
        'manga': manga,
        'chapter': chapter,
        'chapter_list': chapterList,
        'page_list': pageList,
        'page_num': pageNum,
        'page_url': pageUrl,
    }
    if hasNextPage:
        context['next_page'] = nextPage
    if hasPrevPage:
        context['prev_page'] = prev_page
    if hasNextChap:
        context['next_chap'] = nextChapId
    if hasPrevChap:
        context['prev_chap'] = prevChapId
        context['prev_chap_pages'] = prevChapNum
    return render(request, 'reader/pageReader.html', context)


def jumpPage(request, mangaSeries, chapterId):
    pageNum = request.POST['page']
    return HttpResponseRedirect(reverse('reader:pageReader', args=(mangaSeries, chapterId, pageNum,)))


def jumpChapter(request, mangaSeries, display):
    chapterId = request.POST['chapter']
    if display == 'webtoon':
        return HttpResponseRedirect(reverse('reader:stripReader', args=(mangaSeries, chapterId,)))
    elif display == 'pages':
        return HttpResponseRedirect(reverse('reader:pageReader', args=(mangaSeries, chapterId, 1)))
    else:
        raise Http404("URL does not exist")


@permission_required('reader.add_chapter', login_url='accounts:login')
def upload(request, chapterUploaded=""):
    mangaList = Manga.objects.order_by('title')[:]
    context = {
        'manga_list': mangaList,
        'chapter_uploaded': chapterUploaded,
    }
    return render(request, 'reader/upload.html', context)


def submitChapter(request):
    try:
        manga = Manga.objects.get(id=request.POST['manga'])
    except(KeyError, Manga.DoesNotExist):
        mangaList = Manga.objects.order_by('title')[:]
        return render(request, 'reader/upload.html', {
            'manga_list': mangaList,
            'error_message': "You didn't select a manga choice.",
        })
    chapNumber = request.POST['chap_number'].strip()
    volNumber = request.POST['vol_number'].strip()
    if (volNumber == ""):
        volNumber = 0
    if (chapNumber == ""):
        mangaList = Manga.objects.order_by('title')[:]
        return render(request, 'reader/upload.html', {
            'manga_list': mangaList,
            'error_message': "Please enter a chapter number!",
        })
    sortNumber = int((float(volNumber) * 1000000) + (float(chapNumber) * 100))
    title = request.POST['title']
    owner = request.user
    upload_date = timezone.now()

    if os.name == 'nt':
        static = "reader\\static\\"
        path = "reader\\mangas\\" + manga.storage_name
    else:
        static = "static/"
        path = "reader/mangas/" + manga.storage_name

    try:
        os.makedirs(static + path)
    except OSError as e:
        if e.errno != errno.EEXIST:
            mangaList = Manga.objects.order_by('title')[:]
            return render(request, 'reader/upload.html', {
                'manga_list': mangaList,
                'error_message': "Oops something went wrong, please try again.",
            })

    chapterStorageName = str(sortNumber) + upload_date.strftime("%Y-%m-%d_%H-%M-%S_%f")
    if os.name == 'nt':
        path = path + "\\" + chapterStorageName
    else:
        path = path + "/" + chapterStorageName

    try:
        os.makedirs(static + path)
    except OSError as e:
        if e.errno != errno.EEXIST:
            mangaList = Manga.objects.order_by('title')[:]
            return render(request, 'reader/upload.html', {
                'manga_list': mangaList,
                'error_message': "Oops something went wrong, please try again.",
            })

    myfile = request.FILES['chapter_file']
    fs = FileSystemStorage()
    filename = fs.save(myfile.name, myfile)
    uploaded_file_url = fs.url(filename)

    sortedList = []

reader/templates/reader/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>QWERTY Scans | Projects</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'reader/gallery.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pages/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="header">
      <div class="container">
        <a href="{% url 'pages:home' %}">
          <h1>QWERTY Scans</h1>
        </a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <a class="btn" href="{% url 'pages:home' %}">Home</a>
          <a class="btn" href="{% url 'pages:aboutUs' %}">About</a>
          <a class="btn selected" href="{% url 'reader:index' %}">Projects</a>
          <a class="btn" href="{% url 'pages:recruit' %}">Recruitment</a>
          <a class="btn" href="{% url 'pages:contactUs' %}">Contact Us</a>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
        {% if current_list %}
          <h2>Current Projects</h2>
          <div class="gallery">
            {% for manga in current_list %}
              <a href="{% url 'reader:mangaDetail' manga.storage_name %}">
                <div class="picFrame">
                  <img src="{% static manga.pic_location %}" class="image">
                  <div class="overlay">
                    <div class="text">{{ manga.title }}</div>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
        {% endif %}
        {% if completed_list %}
          <h2>Completed Projects</h2>
          <div class="gallery">
            {% for manga in completed_list %}
              <a href="{% url 'reader:mangaDetail' manga.storage_name %}">
                <div class="picFrame">
                  <img src="{% static manga.pic_location %}" class="image">
                  <div class="overlay">
                    <div class="text">{{ manga.title }}</div>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
        {% endif %}
        {% if hiatus_list %}
          <h2>Hiatus Projects</h2>
          <div class="gallery">
            {% for manga in hiatus_list %}
              <a href="{% url 'reader:mangaDetail' manga.storage_name %}">
                <div class="picFrame">
                  <img src="{% static manga.pic_location %}" class="image">
                  <div class="overlay">
                    <div class="text">{{ manga.title }}</div>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
        {% endif %}
        {% if dropped_list %}
          <h2>Dropped Projects</h2>
          <div class="gallery">
            <ul>
              {% for manga in dropped_list %}
                <li><a href="{% url 'reader:mangaDetail' manga.storage_name %}">
                  {{ manga.title }}
                </a></li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
        {% if future_list %}
          <h2>Future Projects</h2>
          <div class="gallery">
            {% for manga in future_list %}
              <a href="{% url 'reader:mangaDetail' manga.storage_name %}">
                <div class="picFrame">
                  <img src="{% static manga.pic_location %}" class="image">
                  <div class="overlay">
                    <div class="text">{{ manga.title }}</div>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
        {% endif %}
        {% if litc_list %}
          <h2>Lost in the Clouds Projects</h2>
          <div class="gallery">
            {% for manga in litc_list %}
              <a href="{% url 'reader:mangaDetail' manga.storage_name %}">
                <div class="picFrame">
                  <img src="{% static manga.pic_location %}" class="image">
                  <div class="overlay">
                    <div class="text">{{ manga.title }}</div>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>

    <div class="footer">
      <div class="container">
        <p>Disclaimer: The all the series worked on here is the property of the original author/artist. <br> QWERTY Scans is not an official distributor. If you like the series, please consider supporting the author by visiting the official site.</p>
        <br/>
        <a href="{% url 'reader:upload' %}">Upload</a>
      </div>
    </div>
  </body>
</html>

reader/templates/reader/manga_details.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>QWERTY Scans | {{ manga.title }}</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pages/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="header">
      <div class="container">
        <a href="{% url 'pages:home' %}">
          <h1>QWERTY Scans</h1>
        </a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <a class="btn" href="{% url 'pages:home' %}">Home</a>
          <a class="btn" href="{% url 'pages:aboutUs' %}">About</a>
          <a class="btn" href="{% url 'reader:index' %}">Projects</a>
          <a class="btn" href="{% url 'pages:recruit' %}">Recruitment</a>
          <a class="btn" href="{% url 'pages:contactUs' %}">Contact Us</a>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
          <img src="{% static manga.pic_location %}">
        <h2>{{ manga.title }}</h2>
          <p><strong>Author: </strong>{{ manga.author }}</p>
          <p><strong>Artist: </strong>{{ manga.artist }}</p>
          <p><strong>Language: </strong>{{ manga.language }}</p>
          <p><strong>Genres: </strong>{{ manga.genres }}</p>
          <p><strong>Status: </strong>{{ manga.get_status_display }}</p>
          {% if manga.is_joint %}
            <p><strong>Joint: </strong>{{ manga.joints|safe }}</p>
          {% endif %}
          <p>{{ manga.description|safe }}</p>
          <br/>
      </div>
      <div class="container">
        {% if chapter_list %}
          <ul>
          {% for chapter in chapter_list %}
            <li><a href="{% url 'reader:readChapter' manga.storage_name chapter.id %}">{{ chapter }}</a></li>
          {% endfor %}
          </ul>
        {% else %}
          <p>No chapters are available.</p>
        {% endif %}
      </div>

      <div class="container">
        <div id="disqus_thread"></div>
        <script>
        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        var disqus_config = function () {
          this.page.url = "https://qwertyscans.com/projects/{{ manga.storage_name }}";  // Replace PAGE_URL with your page's canonical URL variable
          this.page.identifier = "projects/{{ manga.storage_name }}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://qwerty-scans.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
      </div>

    </div>

    <div class="footer">
      <div class="container">
        <p>Disclaimer: The all the series worked on here is the property of the original author/artist. <br> QWERTY Scans is not an official distributor. If you like the series, please consider supporting the author by visiting the official site.</p>
      </div>
    </div>
  </body>
</html>

reader/templates/reader/pageReader.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>QWERTY Scans | Reader</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'reader/reader.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pages/images/favicon.ico' %}" />
    <script src="{% static 'reader/blazy.js' %}"></script>
    <script>
      ;(function() {
        // Initialize
        var bLazy = new Blazy();
      })();
    </script>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <a href="{% url 'pages:home' %}">
          <h1>QWERTY Scans</h1>
        </a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <a class="btn" href="{% url 'pages:home' %}">Home</a>
          <a class="btn" href="{% url 'pages:aboutUs' %}">About</a>
          <a class="btn" href="{% url 'reader:index' %}">Projects</a>
          <a class="btn" href="{% url 'pages:recruit' %}">Recruitment</a>
          <a class="btn" href="{% url 'pages:contactUs' %}">Contact Us</a>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <a href="{% url 'reader:mangaDetail' manga.storage_name %}"><h2>{{ manga.title }}</h2></a>
        <h3>{{ chapter }} - Page {{ page_num }}/{{ chapter.num_pages }}</h3>
      </div>
    </div>

    <div class="reader">
      <div class="buttonPanel">
        <form action="{% url 'reader:jumpChapter' manga.storage_name 'pages' %}" method="post">
          {% csrf_token %}
          <select name="chapter" required="required">
            {% for chap in chapter_list %}
              <option value="{{ chap.id }}">{{ chap }}</option>
            {% endfor %}
          </select>
          <input type="submit" value="Go" />
        </form>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <form action="{% url 'reader:stripReader' manga.storage_name chapter.id %}">
          <input type="submit" value="View" />
        </form>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <form action="{% url 'reader:jumpPage' manga.storage_name chapter.id %}" method="post">
          {% csrf_token %}
          <select name="page" required="required">
            {% for page in page_list %}
              <option value="{{ page }}">{{ page }}</option>
            {% endfor %}
          </select>
          <input type="submit" value="Go" />
        </form>
      </div>
      <div class="buttonPanel">
        {% if prev_chap %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name prev_chap prev_chap_pages %}">&lt;&lt;</a>
        {% endif %}
        {% if prev_page %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name chapter.id prev_page %}">&lt;</a>
        {% endif %}
        {% if next_page %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name chapter.id next_page %}">&gt;</a>
        {% endif %}
        {% if next_chap %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name next_chap 1 %}">&gt;&gt;</a>
        {% endif %}
      </div>
      <div class="picFrame">
      {% if page_url %}
        {% if next_page %}
          <a href="{% url 'reader:pageReader' manga.storage_name chapter.id next_page %}"><img class="b-lazy" src="{% static 'reader/images/kitty.gif' %}" data-src="{% static page_url %}" alt="kitty.gif"/></a>
        {% else %}
          <img class="b-lazy"
          src="{% static 'reader/images/kitty.gif' %}"
          data-src="{% static page_url %}"
          alt="kitty.gif"/>
        {% endif %}
      {% endif %}
      </div>
      <div class="buttonPanel">
        {% if prev_chap %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name prev_chap prev_chap_pages %}">&lt;&lt;</a>
        {% endif %}
        {% if prev_page %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name chapter.id prev_page %}">&lt;</a>
        {% endif %}
        {% if next_page %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name chapter.id next_page %}">&gt;</a>
        {% endif %}
        {% if next_chap %}
          <a class="btn" href="{% url 'reader:pageReader' manga.storage_name next_chap 1 %}">&gt;&gt;</a>
        {% endif %}
      </div>
    </div>

    <div class="footer">
      <div class="container">
        <p>Disclaimer: The all the series worked on here is the property of the original author/artist. <br> QWERTY Scans is not an official distributor. If you like the series, please consider supporting the author by visiting the official site.</p>
      </div>
    </div>
  </body>
</html>